### PR TITLE
[PBW-3857] Responsive Values.

### PR DESCRIPTION
**Pull request by brianfwong**
Responsive values for discovery panel.

### CODE REVIEW

**Comment by mistermendez** [comment]
Discover items now appear on one line and pagination is off -

screen shot 2016-02-08 at 12 27 57 pm

**Comment by mistermendez** [comment]
According to current mocks assets should not scale up in size.

screen shot 2016-02-08 at 12 32 58 pm

**Comment by mistermendez** [comment]
Leave the small (_small.scss) and default medium (_discovery-screen.scss) style as-is and only adjust large style.

**Comment by brianfwong** [comment]
The style document states that large is normal scale, small is 70% scale, medium is normal scale. That would be hard to achieve if I don't adjust small scale.

**Comment by mistermendez** [comment]
1. The medium style in the app is already scaled down to 70%
2. Scale up 30% to achieve large size

This update changes the default medium style to large and the small style to medium. This update should only update the large style.

* small - the item dimensions are the same as medium, the items per page changes to 2 (done)
* medium - item dimensions already scaled down to 70% (done)
* large - scale item dimensions up by 30%

**Comment by brianfwong** [comment]
@mistermendez Adjustments made to limit change to the large size file.

**Comment by mistermendez** [comment]
Sweet :candy:

**Pull request merged**
