### PR TITLE
[PBW-4594] Save user settings to local storage

### PR DESCRIPTION
**Pull request by mistermendez**
⚠️  must merge with:
    * https://github.com/ooyala/skin-config/pull/146
    * https://git.corp.ooyala.com/projects/PBW/repos/mjolnir/pull-requests/98/overview

### CODE REVIEW

**Comment by chibzu** [comment]
LGTM.

**Comment by mistermendez** [comment]
Conflicts in mjolnir update resolved.

**Comment by mistermendez** [comment]
Mjolnir PR - https://git.corp.ooyala.com/projects/PBW/repos/mjolnir/pull-requests/98/overview

**Comment by mistermendez** [comment]
@chibzu finally got the mjolnir build portion of this squared away.

**Comment by chibzu** [comment]
Mjolnir and skin-config PRs look good, merging.

**Pull request merged**
