### PR TITLE
Pbw 4106

### PR DESCRIPTION
**Pull request by chibzu**
Support IMA workflow

### CODE REVIEW

**Comment by mistermendez** [comment]
There is issue with hidden video appearing on player resize

freewheel-ad-black-rect

**Comment by mistermendez** [comment]
* Consider using relative positioning to center. i.e.:
  * `margin: 0 auto;`
  * https://github.com/zurb/foundation-sites/blob/develop/scss/util/_mixins.scss#L195
* Consider using this to visually hide:
  * https://github.com/h5bp/html5-boilerplate/blob/master/src/css/main.css#L124

**Comment by aeng7** [comment]
I made a comment in the JIRA ticket about this. The player_skin_plugins div should keep its size when the player resizes. This will ensure the overlay is centered and the fake video is hidden behind the overlay.

**Comment by chibzu** [comment]
Updated so that the overlay div is always the same size and just stays centered as the player resizes.

**Comment by mistermendez** [comment]
:+1:

**Pull request merged**
