### PR TITLE
[PBW-3757] Prevent embed panel from being resized to larger than cont…

### PR DESCRIPTION
**Pull request by brianfwong**
…ainer.

### CODE REVIEW

**Comment by mistermendez** [comment]
@brianfwong share content is top aligned after this update -

screen shot 2016-08-24 at 4 08 55 pm

screen shot 2016-08-24 at 4 09 33 pm

**Comment by mistermendez** [comment]
I recommend added a new class to the embed form instead of modifying the default style for all forms -

```
<textarea className="oo-form-control oo-embed-form"
```

And using the CSS calc() function to keep it responsive -

```
.oo-share-tab-panel {
  .
  .
  .

  .oo-embed-form {
    resize: none;
    height: calc(15vh);
  }
```

**Comment by mistermendez** [comment]
The xsmall height will likely need to be smaller, add that to 

`/html5-skin/scss/responsive/_xsmall.scss`

**Comment by brianfwong** [comment]
@mistermendez Changed to the calc method. Does 15% for normal and 10% for xsmall look too small?

**Comment by brianfwong** [comment]
@mistermendez @chibzu Re PBW-3757 , Changes made, this pull request needs a review for merging.

**Comment by mistermendez** [comment]
I recommend bumping XS down to 8% so it doesn't overlap the `Share` and `Embed` tab buttons

**Comment by mistermendez** [comment]
screen shot 2016-09-06 at 5 10 28 pm

**Comment by brianfwong** [comment]
@mistermendez Changed it to 8% for xsmall and added a 12px top/bottom margin to prevent it from covering the buttons.

**Comment by mistermendez** [comment]
nice 👍

**Pull request merged**
