### PR TITLE
[PBW-6068] removing blur when upNext or Discovery element is clicked

### PR DESCRIPTION
**Pull request by ksunika**
fixes blurred ads after clicking on upNext or Discovery element

### CODE REVIEW

**Comment by chibzu** [comment]
Do we know why the onWillPlaySingleAd method doesn't remove the blur here?

**Comment by pilievOoyala** [comment]
Is there an onExit method that would be a better place to put this. In case there is a way to change the video without clicking?

**Comment by ksunika** [comment]
@chibzu, onWillPlaySingleAd removes 'oo-blur' but not 'oo-overlay-blur'. Looks like the latter was added to blur overlay ads that video might have.

**Comment by ksunika** [comment]
@pilievOoyala, we don't have a single onExit method here. There are two ways to leave that screen through UI, one is by clicking close and another is by selecting a video. They are handled separately. 

If the video is changed after upNext countdown, it goes through the same  sendDiscoveryClickEvent.

If the video is changed through setEmbedCode, the blurring problem does not occur since the flow is different.

**Comment by chibzu** [comment]
Got it, looks fine by me.

**Comment by mistermendez** [comment]
👍

**Pull request merged**
