### PR TITLE
[PLAYER-509a] Change candidate/latest references to production/latest

### PR DESCRIPTION
**Pull request by dchauOoyala**

### CODE REVIEW

**Comment by rcvrgs** [comment]
are those all the places you needed to update it? LGTM!

**Comment by dchauOoyala** [comment]
Yeah, I missed some in my last PR

**Comment by jpfranco** [comment]
Hmm, I wonder if this was supposed to be merged into master instead of stable. @rcvrgs do you know if Doug mentioned anything about this?

**Comment by aeng7** [comment]
Remaking pull request to merge into master rather than stable.

**Pull request closed without merging**
