### PR TITLE
[PBW-3906] Closed Captions screen converted into scss

### PR DESCRIPTION
**Pull request by ksunika**

### CODE REVIEW

**Comment by ksunika** [comment]
unit tests pending

**Comment by mistermendez** [comment]
this looks great!

**Comment by mistermendez** [comment]
I need to move `calculateScreenSize` function into Skin and made some other minor updates

please review, this is ready to merge if updates approved

**Comment by mistermendez** [comment]
Also, the app returned this warning msg when `calculateScreenSize` was in render() -

> Warning: ClosedCaptionScreen is accessing getDOMNode or findDOMNode inside its render(). 
> render() should be a pure function of props and state. It should never access something that requires 
> stale data from the previous render, such as refs. Move this logic to componentDidMount and 
> componentDidUpdate instead.

**Comment by mistermendez** [comment]
@ksunika conflicts

**Comment by ksunika** [comment]
@mistermendez conflicts resolved

**Comment by mistermendez** [comment]
:+1:

**Pull request merged**
