### PR TITLE
[PBW-4508] changing paths for social icons to absolute

### PR DESCRIPTION
**Pull request by ksunika**
Related PRs: 
https://github.com/ooyala/skin-config/pull/115
http://github.services.ooyala.net/Platform/player-v4/pull/19

### CODE REVIEW

**Comment by mistermendez** [comment]
why 4.1.4 and not 'latest' ?

**Comment by ksunika** [comment]
@mistermendez, as I understand we are not planning to support stable/latest, it is going to be the exact versions. Am I wrong?
When we deploy to stable, the version is updated by build.sh in player-v4 (see http://github.services.ooyala.net/Platform/player-v4/pull/19) so it will be always the correct one for production deploys.

For master, I guess whenever we are changing images or paths, we will update the version as well.

**Comment by rchalooyala** [comment]
^^correct

**Pull request merged**
