### PR TITLE
[PLAYER-167] change countdown time from string to number

### PR DESCRIPTION
**Pull request by ksunika**
should work with https://github.com/ooyala/skin-config/pull/162

### CODE REVIEW

**Comment by ksunika** [comment]
please do not merge before https://github.com/ooyala/skin-config/pull/162 is merged

**Comment by ksunika** [comment]
ooyala/skin-config#162 is merged

**Comment by pilievOoyala** [comment]
Hold off on merging till we sync with PBA on the changes to the JSON structure.

**Comment by ksunika** [comment]
@pilievOoyala , PBA already merged the corresponding skin config changes

**Comment by mistermendez** [comment]
👍

**Pull request merged**
