### PR TITLE
[bugfix/PLAYER-1692]: comented test

### PR DESCRIPTION
**Pull request by yvinokurov**

### CODE REVIEW

**Comment by pilievOoyala** [comment]
Why are we removing these tests?

**Comment by aldigun** [comment]
Why not just removing unused tests?

**Comment by jpfranco** [comment]
These tests are related to accessibility, we shouldn't remove them.

**Comment by IvanSakharovskii** [comment]
@jpfranco Sorry, it's a old PR. I forgot to close it.

**Pull request closed without merging**
