### PR TITLE
[PBW-3913] Adding UI_READY event and workflow for IMA ad rendering.

### PR DESCRIPTION
**Pull request by chibzu**

### CODE REVIEW

**Comment by chibzu** [comment]
Should be merged at the same time as
https://github.com/ooyala/html5-skin/pull/266

**Comment by mistermendez** [comment]
this is https://github.com/ooyala/html5-skin/pull/266 ?

**Comment by chibzu** [comment]
Updated corresponding PR URL.
http://github.services.ooyala.net/Platform/mjolnir/pull/452

**Comment by aldigun** [comment]
Looks good.

**Pull request merged**
